#!/usr/bin/env python3

dna = 'GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCT'

sub_dna = dna[99:200] #cuts out nucleotides 100-200 

print ('Original DNA:''Original DNA:',,sub_dna) #prints nucleotides 100-200

dna_lower = sub_dna.lower() #makes nucleotides lowercase

#next section replaces lowercase with uppercase complement
comp1 = dna_lower.replace('a','T')
comp2 = comp1.replace('t','A')
comp3= comp2.replace('c','G')
comp4 = comp3.replace('g','C')

dna_comp = comp4 #sets final complement sequence

print('Complement:',dna_comp)#prints complement

dna_revcomp = dna_comp[::-1] #creates reverse
print('Reverse Complement:', dna_revcomp) #prints final result


